name: xrformer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.18
  - pip=25.1
  - scipy=1.12.0
  - numpy=1.26.4

  - pip:
    
    --extra-index-url https://download.pytorch.org/whl/cu126
    - torch==2.7.0+cu126
    - torcheval==0.0.7
    - argparse==1.4.0  # Fixed typo and updated version
    - einops==0.8.1
    - -e .