name: xrformer
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9.18
  - pip
  - matplotlib
  - scipy=1.12.0
  - seaborn
  - scikit-image=0.22.0
  - ipykernel
  - pip:
      - torch==2.7.0
      - torchvision
      - torcheval
      - einops
      - tqdm
      - opencv-python
      - scikit-learn
      - -e .
